src/App.jsx

<br/>
- test
<br/>
> test 커밋입니다
Closes #1

feat(#1):test commit

---

package.json
yarn.lock

<br/>
styled-components 설치하고 필요 없는 CSS 파일을 삭제했습니다.
<br/>

feat: styled-components 설치

---

index.html
src/App.jsx
src/style/GlobalStyle.jsx
src/style/theme.js

<br/>
- theme color 설정
- themeProvider 설정 
<br/>
> 추후 원하는 색상은 자유롭게 추가하여서 사용하고 공통된 색상은 논의

style/#8 공통색상팔레트 추가

---

src/components/signup/SignUpPage.jsx
src/pages/SignUp.jsx

<br/>
- SignUpPage 컴포넌트 생성
- form UI 생성
- useState 훅을 사용하여 input 결과 확인
<br/>
> 일단 기본 레이아웃만 잡은 것이니 감안하고 봐주세요!
> 비밀번호 확인 기능은 나중에 넣을 예정이라서 지금은 빼놓았습니다.

Feat: 회원가입 페이지 layout 생성

---

src/pages/Login.jsx

<br/>
- LoginForm 유효성 검사 추가
- 이메일 변수명 변경 (email -> InputEmail)
- 페이지 레이아웃 전과동
<br/>
<br/>
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요  
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
Closes #<issue-number>

Feat: 로그인 입력사항 검사

---

src/pages/MyPage.jsx
src/pages/SignUp.jsx

<br/>
- 비밀번호 입력 값과 비밀번호 확인에서 입력한 값을 비교하는 로직을 추가했습니다. 
- 비밀번호가 노출되지 않게 type을 password로 바꾸고 이메일도 email로 변경했습니다.
<br/>

feat: 비밀번호 확인 로직 추가, 비밀번호 input type 변경

---

src/contexts/AuthProvider.jsx

<br/>
- 코드 변경은 딱히 없습니다
<br/>
<br/>
> RLS를 항상 항상 꼭 정말로 제발로 확인합시다 여러분

fix/RLS 추가

---

eslint.config.js
src/contexts/AuthProvider.jsx
src/pages/MyPage.jsx

<br/>
- AuthProvider.jsx에서 소개글 받아오는 로직 추가
- 마이페이지 내에서 user 불러오기
<br/>

Feat: Supabase에서 user 소개글 불러오기

---

src/pages/Post.jsx
src/style/Post/Post.style.jsx

<br/>
- supabase Posts 테이블이랑 연결
- 카테고리, 제목, 내용 모두 작성 해야 등록
- 등록 시 Home 페이지로 이동 (현재 주석 처리)
<br/>
<br/>

feat : supabase posts data 연동

---

src/components/Layout/Header.jsx
src/components/Layout/Nav.jsx
src/style/StLayout/Header.style.jsx

<br/>
navbar에 login시 나타나는 UI를 변경하였습니다
기존에 login, logout 상태를 임시로 표시하던 button이 삭제되고 context의 user.session에서 로그인 상태를 공유합니다.
<br/>
<br/>

Feat/header login check: 로그아웃 버튼 기능 추가 및 로그인 시 유저 닉네임 표시 

---

src/components/Layout/Header.jsx
src/components/Layout/Nav.jsx
src/style/StLayout/Header.style.jsx

<br/>
변경된 Styled-component 명이 적용되지 않은 부분이 있어 페이지가 로드되지 않음
-> AuthLinkWrapper 에서 LinksWrapper로 사용하여 전체 적용 
<br/>

hotfix: header error 수정 

---

src/components/Layout/FloatBtn.jsx
src/components/Layout/Header.jsx
src/components/Layout/Layout.jsx
src/contexts/AuthProvider.jsx
src/pages/Login.jsx
src/shared/Router.jsx
src/style/StLayout/FloatBtn.Style.jsx
src/style/StLayout/Header.style.jsx

<br/>
- 오른쪽 페이지 하단에 Float 버튼을 표시합니다. 
- 클릭시  페이지 이동후 버튼메뉴 사라짐
<br/>
<br/>

Feat/float button :  Float버튼을 통한 페이지 이동 구현

---

src/contexts/AuthProvider.jsx
src/pages/Login.jsx
src/shared/ProtectedRoute.jsx
src/shared/Router.jsx

<br/>
- ProtectedRouter를 통해 로그인 여부에 따른 페이지 라우팅
- isLogin의 useState를 'initial'로 변경하여 isLogin의 상태가 true나 false일 경우에 ProtectedRouter가 작동하도록 구현  
<br/>
> 페이지 이동 시 문제가 생기면 바로 슬랙 주세요~

fix: 새로고침 시 로그인 페이지로 이동하던 문제 해결

---

src/components/MyPage/MyPostList.jsx
src/pages/MyPage.jsx

<br/>
- 마이페이지의 스타일을 수정했습니다.
<br/>
https://github.com/user-attachments/assets/275edd68-8a62-4afa-975b-3b5424ea11f5
<br/>
> 일요일 밤까지 참석이 어려울 것 같아서 미리 올려놓습니다!

Style: 마이페이지 스타일 수정

---

src/pages/Post.jsx

<br/>
- 카테고리 제목 내용 입력해도 제출이 안되는 부분 해결
<br/>
<br/>

fix : 제출 안되던 부분 해결

---

src/pages/Detail.jsx

<br/>
- 구조분해 할당 내 변수명 오류 수정
<br/>

fix : 변수명 실수 수정

---

src/pages/Login.jsx
src/style/Auth/Auth.Input.style.jsx
src/style/Login/Login.style.jsx
src/style/StCommon/Button.style.jsx

1. input - label 연결하기
2. 전체 적인 CSS 수정 
<br/>

Feat/login refactor : login 페이지 변경 

---

src/pages/Login.jsx

- merge 과정에서 사라진 Login.jsx 복구..
<br/>

fix: 이전 Login.jsx 코드 복구 완료

---

src/pages/Login.jsx
src/style/Login/Login.style.jsx

style: 스타일 변경

---

src/components/common/CategoryBadge.jsx
src/pages/Detail.jsx

<br/>
- 게시물 창 닫기 기능 추가
- 게시물 삭제 및 수정
- 게시물 카테고리 뱃지 공통 컴포넌트화
- 댓글 삭제 
- 위 사항 전제조건 : 해당 게시물이 본인의 게시물일 경우 수정/삭제 버튼 노출됨.
<br/>
https://github.com/user-attachments/assets/f59b4f61-6b5a-4110-85fd-4ac213a0b57a
<br/>
> 홈 피드 상 하단에 위치한 게시물을 창닫기하면 맨 위로 올라옵니다.
> home.jsx 상에서 이전 스크롤 위치를 세션에 저장해 놓도록 해보기도 했는데
> 세션에 스크롤 위치는 저장이 되는데 그 위치로 돌아가진 않았습니다. 
> 해결방안 있으신 분 ^^..

Feat/detail ver 2 기능 및 스타일 변경

---

src/pages/Post.jsx
src/style/Post/Post.style.jsx
src/style/StLayout/Layout.style.jsx
src/utils/category.jsx
src/utils/validateFile.js

<br/>
- 미리보기 부분 추가
- 이미지 파일만 올릴 수 있도록 수정
- 미디어 쿼리 480px 1024px 설정
<br/>
<br/>
> MYpage에서도 파일 유효성 검사 필요하시면 바로 가져다가 쓰시면 됩니다.

feat: post페이지 파일 미리보기 추가, 파일 유효성 검사 추가, 미디어쿼리 설정

---

src/api/api.js
src/components/Layout/Footer.jsx
src/components/Layout/Layout.jsx
src/components/MyPage/MyPostList.jsx
src/components/MyPage/supabase.jsx
src/pages/Home.jsx
src/style/StLayout/Header.style.jsx
src/style/theme.js

- footer에 멤버별 github링크 연결 추가
- header 색상 변경
- home의 api 함수 분리 
- 
<br/>

Feat/layout refactor : footer 및 header 추가 작업 

---

src/pages/Post.jsx
src/style/Post/Post.style.jsx
src/utils/category.jsx

<br/>
- 카테고리 클릭시 이벤트 추가
<br/>
<br/>

feat : 카테고리 비주얼 업데이트

---

src/pages/Post.jsx
src/style/Post/Post.style.jsx

style : post페이지 전반적인 스타일 수정

---

src/pages/Post.jsx
src/style/Post/Post.style.jsx
src/utils/category.jsx

<br/>
- 게시물 게시 안되고 예외처리 되는 점 수정
<br/>

bugfix : 게시물 게시 안되는 부분 수정

---

src/pages/post/Post.jsx
src/pages/post/postStyle/Post.style.jsx

<br/>
- 이미지 파일이 label을 뚫고 넘거나는 현상 수정
- 미디어쿼리 768px 추가
<br/>
<br/>

style : 768 반응형 추가, 이미지 파일 수정
